// Display labels only: serialized identifiers remain unchanged.
const labels: Record<string, string> = {
"3/4 Turn":"Поворот 3/4","Adds a visual directly to the entity.":"Добавляет рисунок прямо к объекту.","All features":"Все черты лица","All paint":"Всё оформление","All roles":"Все назначения","Animal / Mount":"Животное / ездовое","Animation Pack":"Набор анимаций","Attachment":"Крепление","Attachment Transform":"Положение крепления","BASE":"ОСНОВНОЙ","Base":"Основа","Back":"Назад","Beard":"Борода","Big Head":"Большая голова","Both":"Оба","Broad Torso":"Широкое туловище","Brows":"Брови","By Feature":"По черте лица","Cancel":"Отмена","Character":"Персонаж","Closed pencil: drag to draw a filled closed shape.":"Перетащите указатель, чтобы нарисовать замкнутую фигуру с заливкой.","Combat":"Бой","Compact":"Компактный","Compact Arms":"Короткие руки","Creates a project item and equips it immediately.":"Создаёт предмет проекта и сразу надевает его.","Custom":"Свои настройки","Custom path":"Свой контур","Default Fit Transform":"Базовая подгонка","Detail":"Деталь","Dot Cute":"Точки","Download review ZIP":"Скачать проверку в ZIP","Drag SVG, PNG, WebP or JPEG files here":"Перетащите сюда SVG, PNG, WebP или JPEG","Drag shape to move. Click empty space to place pivot.":"Перетащите фигуру для перемещения. Нажмите на пустое место для установки точки опоры.","Drag shape to move. Use the handles to rotate and resize. Click empty space to place pivot.":"Перетащите фигуру. Используйте маркеры для поворота и размера. Нажмите на пустое место для установки точки опоры.","Draw On Head keeps the face workflow locked to the head overlay context while you paint.":"Режим рисования на голове сохраняет связь с выбранной деталью лица.","Drop assets here":"Перетащите файлы сюда","Dwarf":"Коренастый","Edit template slot positions for the active template":"Редактировать положение креплений текущей основы","Edit the equipped item part for the selected slot":"Изменить часть предмета на выбранном креплении","Empty":"Пусто","Erase Pass":"Стирание","Eraser: click or drag across shapes to remove them.":"Нажмите или проведите по фигурам, чтобы удалить их.","Eyes":"Глаза","Face presets, transforms and overlays update this preview through the same evaluated character pipeline.":"Предпросмотр учитывает варианты лица, положение и свои рисунки.","Feature + Role":"Черта лица + назначение","Feature + Role + Paint":"Черта лица + назначение + оформление","Fill Pass":"Заливка","Fringe Long":"Длинная чёлка","Fringe Short":"Короткая чёлка","Frown":"Нахмуренный","Full Short":"Короткая борода","Generating…":"Подготовка…","Generic":"Произвольный","Hair":"Волосы","Head focus is active: keep painting while watching the face overlay in the same runtime stack.":"Рисуйте на голове и проверяйте результат в предпросмотре.","Heavy Steps":"Тяжёлая поступь","Heroic":"Герой","Hide gizmo":"Скрыть маркеры крепления","Highlight":"Блик","LOWER":"НИЗ","Lean Torso":"Узкое туловище","Line":"Линия","Line Pass":"Обводка","Lock Aspect: Off":"Пропорции: свободные","Lock Aspect: On":"Пропорции: фиксированные","Lock gizmo":"Заблокировать маркеры","Long Legs":"Длинные ноги","Long Reach":"Длинные руки","Messy Short":"Короткие взъерошенные","Mirror X":"Отразить по X","Monster":"Существо","Mouth":"Рот","Neutral":"Нейтральный","No Symmetry":"Без симметрии","No overlay selected":"Рисунок лица не выбран","Open Or Create Generic Overlay":"Открыть или создать рисунок лица","Open Smile":"Открытая улыбка","Pause":"Пауза","Peasant outfit":"Крестьянская одежда","Pencil: drag to draw a smooth freehand stroke.":"Перетащите указатель, чтобы нарисовать плавную линию.","Play":"Воспроизвести","Pose":"Поза","Required":"Обязательное","Rogue":"Ловкач","Round Kawaii":"Круглые","Select Overlay":"Выберите рисунок лица","Select visuals and slots without transforming them":"Выбирать рисунки и крепления без изменения положения","Selected":"Выбрано","Shadow":"Тень","Short Goatee":"Короткая эспаньолка","Show gizmo":"Показать маркеры","Sleepy":"Сонный","Slots":"Крепления","Small Head":"Маленькая голова","Soft Arc":"Мягкая дуга","Soft Smile":"Лёгкая улыбка","Static Object":"Объект окружения","Stern":"Строгий","Tall":"Высокий","Tiny Smile":"Маленькая улыбка","Tuft":"Хохолок","UPPER":"ВЕРХ","Unlock gizmo":"Разблокировать маркеры","Uses the same evaluated scene path as canvas and export. When editing an item part, this preview isolates the current equipped slot.":"Предпросмотр использует ту же сцену, что холст и экспорт. При редактировании части предмета показано только её крепление.","Wide Shine":"Широкие с бликом","Worried":"Обеспокоенный","all features":"все черты лица","any":"любой","blank":"пустой","combined":"общий","custom":"свой","default":"по умолчанию","doc-linked overlay":"рисунок связан с документом","empty":"пусто","end":"конец","identity":"без изменений","loops":"зациклен","off":"выкл.","on":"вкл.","once":"один раз","overlay without saved doc link":"рисунок без документа","per anim":"на клип","per entity":"на объект","root":"Корень","start":"начало","template":"основа","visible":"видимый","Helmets":"Головные уборы","Face":"Лицо","Neck":"Шея","Hands":"Кисти","Waist":"Пояс","Feet":"Стопы","Cloaks":"Плащи","Main Weapon":"Основное оружие","Off-hand":"Вторая рука","Shields":"Щиты","Rings":"Кольца","Amulets":"Амулеты","Horns":"Рога","Wings":"Крылья","Tails":"Хвосты","Saddles":"Сёдла","Packs":"Сумки","Shells":"Панцири","Static Part":"Деталь окружения","Auto":"Автоматически","Center":"Центр","Front":"Спереди","Chest":"Грудь","Back / Spine":"Спина / позвоночник","Pelvis / Waist":"Таз / пояс","Left Shoulder":"Левое плечо","Right Shoulder":"Правое плечо","Left Hand":"Левая кисть","Right Hand":"Правая кисть","Left Hip":"Левое бедро","Right Hip":"Правое бедро","Left Knee / Shin":"Левое колено / голень","Right Knee / Shin":"Правое колено / голень","Left Foot":"Левая стопа","Right Foot":"Правая стопа","Head Size":"Размер головы","Neck Length":"Длина шеи","Torso Height":"Высота туловища","Torso Width":"Ширина туловища","Arm Length":"Длина плеча","Forearm Length":"Длина предплечья","Hand Size":"Размер кисти","Leg Length":"Длина бедра","Shin Length":"Длина голени","Foot Size":"Размер стопы","Pelvis Width":"Ширина таза","Overall Height":"Общий рост","Global":"Общие","Idles (Torso)":"Покой (туловище)","Locomotion":"Передвижение","Reactions":"Реакции","Actions":"Действия","Social & Fun":"Общение","Quadruped":"Четвероногие","Bird":"Птицы","Siege":"Осадные машины","Biped Profile - Bare Chibi":"Чиби в профиль","Biped Profile - Bare Chibi Slim":"Стройный чиби в профиль","Biped Profile - Bare Chibi Sturdy":"Крепкий чиби в профиль",
  "pencil":"Карандаш", "picker":"Пипетка", "pen":"Перо", "rectangle":"Прямоугольник", "pivot":"Точка опоры", "add-vertex":"Добавить вершину", "linear":"Линейное", "ease_in":"Ускорение", "ease_out":"Замедление", "ease_in_out":"Плавное", "step":"Ступенька",
  "% complete": "% готово",
  "% · Grip": "% · хват",
  "(affects item filtering)": "(влияет на подбор предметов)",
  "(this entity only)": "(только этот объект)",
  "1.8m Scale": "Рост 1,8 м",
  "Active Animation": "Текущая анимация",
  "Active Face Feature": "Выбранная черта лица",
  "Active template:": "Текущая основа:",
  "Add / Replace Key": "Добавить / заменить ключ",
  "Add Child Bone": "Добавить дочернюю кость",
  "Add Ellipse": "Добавить эллипс",
  "Add Path": "Добавить контур",
  "Add Rect": "Добавить прямоугольник",
  "Add marker": "Добавить маркер",
  "All": "Все",
  "All parts": "Все части",
  "All slots compatible": "Все крепления совместимы",
  "Allowed": "Разрешено",
  "Anatomical owner": "Анатомическая принадлежность",
  "Anchor": "Точка крепления",
  "Anchor ID": "Идентификатор крепления",
  "Animation Clips": "Клипы анимации",
  "Animation Preview": "Предпросмотр анимации",
  "Animation X-Ray": "Диагностика анимации",
  "Animation X-Ray joints": "Суставы на диагностике",
  "Animation X-Ray legend": "Обозначения диагностики",
  "Animation X-Ray mode": "Режим диагностики",
  "Animation data": "Данные анимации",
  "Animation time": "Время анимации",
  "Animation validation warnings": "Проверка анимации",
  "Anti-alias": "Сглаживание",
  "Apply": "Применить",
  "Apply Brush Preset": "Применить настройки кисти",
  "Arms": "Руки",
  "Art Studio": "Рисунок и слои",
  "Artwork document": "Документ рисунка",
  "Artwork layers": "Слои рисунка",
  "Artwork name": "Название рисунка",
  "Artwork preview": "Предпросмотр рисунка",
  "Asset": "Объект",
  "Assigned Parts": "Назначенные части",
  "Atlas Mode": "Компоновка атласа",
  "Attached bone": "Связанная кость",
  "Attachment Override": "Подгонка крепления",
  "Auto Key": "Автоключ",
  "Back To Attachment Override": "Вернуться к креплению",
  "Background": "Фон",
  "Beard Overlay": "Рисунок бороды",
  "Behavior:": "Поведение:",
  "Bind to Bone / Rigid": "Жёстко привязать к кости",
  "Blend": "Смешивание",
  "Body Focus": "Область тела",
  "Body Intent": "Задача редактирования тела",
  "Body Morph": "Пропорции тела",
  "Body Morph Workspace": "Редактор пропорций",
  "Body Regions": "Области тела",
  "Bone": "Кость",
  "Bone ID": "Идентификатор кости",
  "Bone Part": "Часть на кости",
  "Bone length": "Длина кости",
  "Bone name": "Название кости",
  "Bone parent": "Родитель кости",
  "Bone:": "Кость:",
  "Brows Overlay": "Рисунок бровей",
  "Cancel export": "Отменить экспорт",
  "Canvas Focus": "Область холста",
  "Category": "Категория",
  "Category:": "Категория:",
  "Center Pivot": "Опора по центру",
  "Choose artwork": "Выберите рисунок",
  "Choose replacement bone": "Выберите заменяющую кость",
  "Clear Selection": "Снять выделение",
  "Clear lower body override": "Сбросить клип нижней части",
  "Clear upper body override": "Сбросить клип верхней части",
  "Clip name": "Название клипа",
  "Clips": "Клипы",
  "Close": "Закрыть",
  "Closed Pencil": "Замкнутый контур",
  "Compatibility": "Совместимость",
  "Composer": "Сборка",
  "Configure and export sprite sheets, atlases, and SVG packs for your entities.": "Выберите формат и параметры экспорта открытого объекта.",
  "Content Bounds": "Границы рисунка",
  "Copy Key": "Копировать ключ",
  "Copy to New Layer": "Копировать на новый слой",
  "Create Rig": "Создать скелет",
  "Create artwork or open an existing document to draw, rig and animate.": "Создайте или откройте рисунок для рисования, привязки и анимации.",
  "Created": "Создано",
  "Custom Item": "Свой предмет",
  "Cut to New Layer": "Вырезать на новый слой",
  "Dark = FAR · Base = CROSS_BODY/BODY · Bright = NEAR/FRONT": "Тёмный — сзади · обычный — на теле · яркий — спереди",
  "Dark = FAR · base = BODY/CROSS · light = NEAR/FRONT": "Тёмный — сзади · обычный — на теле · светлый — спереди",
  "Debug": "Диагностика",
  "Debug skeleton": "Показать скелет",
  "Default Fit Editing": "Редактирование базовой подгонки",
  "Deformation": "Деформация",
  "Delete": "Удалить",
  "Delete Bone": "Удалить кость",
  "Delete Key": "Удалить ключ",
  "Delete Selected Vertex": "Удалить вершину",
  "Depth Colors": "Цвета глубины",
  "Depth Layers": "Слои глубины",
  "Depth shading": "Оттенки глубины",
  "Depth slot colors": "Цвета уровней глубины",
  "Description": "Описание",
  "Detach Source": "Отсоединить исходник",
  "Detailed Vector Editor": "Векторные контуры",
  "Distance:": "Расстояние:",
  "Document": "Документ",
  "Document View": "Вид документа",
  "Documents": "Документы",
  "Down": "Ниже",
  "Download export": "Скачать результат ещё раз",
  "Draft Paint": "Оформление рисунка",
  "Draft Role": "Назначение рисунка",
  "Draft Symmetry": "Симметрия рисунка",
  "Draw": "Рисовать",
  "Draw Attached Part": "Нарисовать связанную часть",
  "Draw Mode": "Режим рисования",
  "Draw On Head": "Рисовать на голове",
  "Draw Order Inspector": "Порядок отрисовки",
  "Draw Order ·": "Порядок отрисовки ·",
  "Draw at least one visible shape to compute bounds.": "Нарисуйте хотя бы одну видимую фигуру, чтобы вычислить границы.",
  "Duplicate": "Дублировать",
  "Duplicate Clip": "Дублировать клип",
  "Duration ms": "Длительность, мс",
  "Edit": "Редактировать",
  "Edit Default Fit": "Базовая подгонка",
  "Edit Mesh": "Изменить сетку",
  "Edit Source Asset": "Изменить исходный рисунок",
  "Edit Weights": "Изменить веса",
  "Empty Rig": "Пустой скелет",
  "Empty slot — pick an item from the Items tab.": "Крепление пустое — выберите предмет во вкладке «Предметы».",
  "Entities": "Объекты",
  "Entity Type": "Тип объекта",
  "Entity Visual": "Рисунок объекта",
  "Entity Visuals": "Рисунки объекта",
  "Equipment Depth ·": "Глубина экипировки ·",
  "Equipment depth layer": "Слой глубины экипировки",
  "Equipment depth part": "Часть экипировки",
  "Equipment depth slot": "Уровень глубины экипировки",
  "Equipped (": "Надето (",
  "Equipped Item": "Надетый предмет",
  "Erase": "Стереть",
  "Eraser": "Ластик",
  "Existing skeleton preset": "Готовая основа скелета",
  "Export": "Экспортировать",
  "Export Animation Review": "Скачать проверку анимации",
  "Export Studio": "Экспорт объекта",
  "Export Summary": "Состав экспорта",
  "Export arm diagnostics": "Скачать диагностику рук",
  "Exporting…": "Экспортируем…",
  "Eyes Overlay": "Рисунок глаз",
  "FPS": "Кадров/с",
  "Face Brush Preset": "Настройки кисти для лица",
  "Face Editor": "Редактор лица",
  "Face Focus": "Область лица",
  "Face Local": "Координаты лица",
  "Face Mode": "Режим лица",
  "Face Overlay": "Рисунок лица",
  "Face Overlays": "Рисунки лица",
  "Face Workspace": "Работа с лицом",
  "Feature": "Черта лица",
  "Feature Controls": "Параметры черты лица",
  "Feature Tag": "Метка черты лица",
  "Feet Pivot": "Опора у ног",
  "Files:": "Файлы:",
  "Fill": "Заливка",
  "Fill Bucket": "Заливка области",
  "Fine-tune the rig by nudging individual bones. These offsets are saved with the character.": "Настройте исходное положение отдельных костей. Смещения сохраняются с персонажем.",
  "Fit": "Вписать",
  "Fit entity in view": "Вписать объект в окно",
  "Flip X": "Отразить по X",
  "Flip Y": "Отразить по Y",
  "Focus": "Область",
  "Focus Body Region": "Показать область тела",
  "Focus:": "Область:",
  "Frame Size (px)": "Размер кадра, пиксели",
  "Frames": "Кадры",
  "Full Vector": "Цельный векторный рисунок",
  "Generic Overlay": "Произвольный рисунок",
  "Grip": "Хват",
  "Grouping": "Группировка",
  "Hair Overlay": "Рисунок волос",
  "Hands cover grip": "Кисти закрывают рукоять",
  "Head": "Голова",
  "Head forbidden core": "Запретная область головы",
  "Height": "Высота",
  "Hide All Slots": "Скрыть все крепления",
  "ID": "Идентификатор",
  "Import": "Импортировать",
  "Import Art": "Импорт рисунка",
  "Import Asset": "Импорт части или предмета",
  "Imported Parts": "Импортированные части",
  "Imported armor, hair, face detail...": "Броня, волосы, детали лица…",
  "Influencing bones": "Влияющие кости",
  "Inspector": "Свойства",
  "Intent": "Задача",
  "Item": "Предмет",
  "Item Name": "Название предмета",
  "Item Part": "Часть предмета",
  "Joint labels": "Подписи суставов",
  "Joint trajectory": "Траектория сустава",
  "Key easing": "Сглаживание ключа",
  "Key time": "Время ключа",
  "Large authoring workspace for editing item parts, entity visuals and face overlays without squeezing tools into the timeline panel.": "Редактор контуров частей предметов, рисунков объекта и деталей лица.",
  "Layer group": "Группа слоя",
  "Layer name": "Название слоя",
  "Layer opacity": "Непрозрачность слоя",
  "Layered stack": "Послойная сборка",
  "Layers": "Слои",
  "Left": "Слева",
  "Legs": "Ноги",
  "Length": "Длина",
  "License": "Лицензия",
  "License conflicts detected": "Обнаружены различия лицензий",
  "Live Character Preview": "Предпросмотр на персонаже",
  "Live Rig Preview": "Предпросмотр скелета",
  "Locked": "Заблокирован",
  "Loop": "Зациклить",
  "Lower-body clip override (plays simultaneously with base clip)": "Клип нижней части тела (одновременно с основным)",
  "Make Flexible": "Сделать гибким",
  "Markers are saved only with “Save markers to clip”. Rig Colors always includes depth shading. Equipment and joint labels follow the current X-Ray settings.": "Маркеры сохраняются кнопкой «Сохранить маркеры в клип». Цвета скелета учитывают глубину. Экипировка и подписи зависят от настроек диагностики.",
  "Markers saved to clip.": "Маркеры сохранены в клип.",
  "Mesh quality": "Качество сетки",
  "Metadata": "Дополнительные данные",
  "Mirror H": "Отразить горизонтально",
  "Mirror V": "Отразить вертикально",
  "Mode:": "Режим:",
  "Morph Mode": "Режим пропорций",
  "Morph Sliders ·": "Пропорции ·",
  "Morph changes apply directly to the active entity and re-render here in the same authoring flow.": "Изменения пропорций сразу видны на открытом объекте.",
  "Mouth Overlay": "Рисунок рта",
  "Name": "Название",
  "Name:": "Название:",
  "Naming Template": "Шаблон имени файла",
  "New": "Создать",
  "New Artwork": "Новый рисунок",
  "New Clip": "Новый клип",
  "New Overlay": "Новый рисунок лица",
  "New Overlay Draft": "Новый набросок лица",
  "Next": "Далее",
  "Next Part": "Следующая часть",
  "No clips for this family.": "Нет клипов для этого скелета.",
  "No clips selected — only rest pose will be exported.": "Клипы не выбраны — экспортируется только исходная поза.",
  "No custom face overlays for the current feature.": "Нет своих рисунков для выбранной черты лица.",
  "No depth metadata = neutral gray.": "Без данных глубины — нейтральный серый.",
  "No editor documents yet.": "Пока нет документов рисунков.",
  "No entity selected.": "Откройте объект.",
  "No entity selected. Select an entity to export.": "Откройте объект для экспорта.",
  "No face overlays yet. Create one to start drawing.": "Создайте рисунок лица, чтобы начать рисовать.",
  "No group": "Без группы",
  "No items equipped. Use the Slots tab to equip items.": "Нет экипировки. Выберите предметы в разделе «Экипировка».",
  "No keyframe tracks in this clip.": "В этом клипе нет дорожек с ключами.",
  "No overlays for this feature.": "Для этой черты лица пока нет рисунков.",
  "No parent": "Без родителя",
  "No preview": "Нет предпросмотра",
  "No state machine available. Create an entity first.": "У этого объекта нет графа состояний. Здесь можно только просматривать готовые графы.",
  "No templates for this entity type yet.": "Пока нет основ для этого типа объекта.",
  "None": "Нет",
  "Normal": "Обычный вид",
  "Not set — click to add": "Не задано — нажмите, чтобы добавить",
  "Offset X": "Смещение X",
  "Offset Y": "Смещение Y",
  "Onion Skin": "Соседние кадры",
  "Only": "Только",
  "Opacity": "Непрозрачность",
  "Open In Editor": "Открыть рисунок",
  "Open In Face Mode": "Редактировать лицо",
  "Open In Sprite Editor": "Открыть рисунок",
  "Open Overlay Editor": "Редактировать рисунок лица",
  "Open Selected": "Открыть выбранное",
  "Open the browser console for the full component stack.": "Подробности ошибки доступны в консоли браузера.",
  "Open the selected item part or entity visual, draw vector shapes, then save back into the project.": "Выберите часть предмета или рисунок объекта. Изменения рисунка обновляют связанный объект.",
  "Outline px": "Обводка, пиксели",
  "Output Formats": "Форматы экспорта",
  "Overall": "Общее",
  "Overlay Documents ·": "Рисунки лица ·",
  "Overlay Focus": "Область рисунка",
  "Overlay Local": "Координаты рисунка",
  "Overlay Name": "Название рисунка",
  "Overrides the scene style for this entity. Use the toolbar to reset all entities at once.": "Стиль этого объекта. Общий стиль персонажей можно изменить в настройках проекта.",
  "Paint Filter": "Фильтр оформления",
  "Paint Pass": "Оформление",
  "Paint color": "Цвет кисти",
  "Palette": "Палитра",
  "Palette Override": "Своя палитра",
  "Parametric face settings stay in the inspector, while custom overlays and draw-over parts live here.": "Основные параметры лица находятся во «Внешности». Здесь рисуются свои детали лица.",
  "Parent": "Родитель",
  "Part": "Часть",
  "Part Mapping": "Назначение частей",
  "Parts:": "Части:",
  "Paste Key": "Вставить ключ",
  "Path Data": "Данные контура",
  "Pencil": "Карандаш",
  "Phase": "Фаза",
  "Pivot": "Точка опоры",
  "Pivot X": "Опора X",
  "Pivot Y": "Опора Y",
  "Pixel": "Пиксельный",
  "Pixel filtering": "Сглаживание пикселей",
  "Pose:": "Поза:",
  "Presets": "Готовые настройки",
  "Prev Part": "Предыдущая часть",
  "Preview": "Предпросмотр",
  "Preview (": "Предпросмотр (",
  "Preview Layers": "Слои предпросмотра",
  "Preview:": "Предпросмотр:",
  "Profile": "Профиль",
  "Quick Body Actions ·": "Действия с телом ·",
  "Quick Overlay Actions": "Действия с рисунком лица",
  "Rasterize Copy": "Растровая копия",
  "Reassign and Delete Bone": "Переназначить связи и удалить кость",
  "Reassign dependents to": "Перенести связи на кость",
  "Recalculate Weights": "Пересчитать веса",
  "Redo": "Повторить",
  "Reference": "Подложка",
  "Reference only": "Только подложка",
  "Regenerate Mesh": "Пересоздать сетку",
  "Remove": "Убрать",
  "Remove from character": "Снять с персонажа",
  "Reset": "Сбросить",
  "Reset All": "Сбросить всё",
  "Reset Balanced": "Сбросить пропорции",
  "Reset Bone": "Сбросить кость",
  "Reset Overlay Transform": "Сбросить положение рисунка",
  "Reset Position": "Сбросить положение",
  "Reset Rotation": "Сбросить поворот",
  "Reset Scale": "Сбросить масштаб",
  "Reset To Item Default": "Вернуть настройки предмета",
  "Reset slot transform": "Сбросить положение крепления",
  "Reset zoom": "Сбросить масштаб",
  "Resize shape": "Размер фигуры",
  "Rest Pose": "Исходная поза",
  "Rest Rotation": "Исходный поворот",
  "Rest Scale X": "Исходный масштаб X",
  "Rest Scale Y": "Исходный масштаб Y",
  "Rest TX": "Исходное смещение X",
  "Rest TY": "Исходное смещение Y",
  "Rest pose ·": "Исходная поза ·",
  "Restore Flexible": "Восстановить гибкость",
  "Rig Colors": "Цвета скелета",
  "Rig debug": "Диагностика скелета",
  "Right": "Справа",
  "Role": "Назначение",
  "Role Filter": "Фильтр назначений",
  "Root Transform": "Положение объекта",
  "Rot +": "Поворот +",
  "Rot -": "Поворот −",
  "Rotate +90": "Повернуть +90°",
  "Rotate -90": "Повернуть −90°",
  "Rotate shape": "Поворот фигуры",
  "Rotation": "Поворот",
  "Rotation Starter": "Пример вращения",
  "Rotation interpolation": "Интерполяция поворота",
  "Runtime error": "Ошибка приложения",
  "SL/EL/HL · SR/ER/HR: shoulder / elbow / hand. N/F: near / far.": "SL/EL/HL · SR/ER/HR: плечо / локоть / кисть. N/F: ближний / дальний.",
  "Save Fit For Skeleton Family": "Сохранить подгонку для семейства скелетов",
  "Save Fit For This Template": "Сохранить подгонку для этой основы",
  "Save markers to clip": "Сохранить маркеры в клип",
  "Scale": "Масштаб",
  "Scale +": "Масштаб +",
  "Scale -": "Масштаб −",
  "Scale X": "Масштаб X",
  "Scale Y": "Масштаб Y",
  "Select": "Выделение",
  "Select an animation clip to view its keyframe tracks.": "Выберите клип, чтобы увидеть дорожки с ключами.",
  "Select an entity to inspect its properties.": "Откройте объект, чтобы увидеть свойства.",
  "Select an entity to view its slots.": "Откройте объект, чтобы увидеть крепления.",
  "Select at least one format.": "Выберите хотя бы один формат.",
  "Select or create an entity": "Откройте или создайте объект",
  "Selected Slot:": "Выбранное крепление:",
  "Selected bone": "Выбранная кость",
  "Selected vertex weight": "Вес выбранной вершины",
  "Set depth key": "Добавить ключ глубины",
  "Setup / inherited": "Исходное / наследуется",
  "Setup equipment far layer": "Дальний слой экипировки",
  "Setup equipment near layer": "Ближний слой экипировки",
  "Shape": "Фигура",
  "Shape Properties": "Свойства фигуры",
  "Shapes": "Фигуры",
  "Shared Attachment Override": "Общая подгонка крепления",
  "Sheet per entity": "Отдельный лист для каждого объекта",
  "Shortest": "Кратчайший путь",
  "Shoulder roots": "Начала плеч",
  "Show All Slots": "Показать все крепления",
  "Show equipment": "Показать экипировку",
  "Single-file or multi-part item import is supported": "Можно импортировать один файл или набор частей предмета",
  "Size": "Размер",
  "Skeleton": "Скелет",
  "Skeleton Pose": "Поза скелета",
  "Skeleton preset": "Основа скелета",
  "Slot": "Крепление",
  "Slot Overrides": "Настройки креплений",
  "Slot Transform": "Положение крепления",
  "Slot:": "Крепление:",
  "Smooth": "Плавное",
  "Source File:": "Исходный файл:",
  "Species": "Вид",
  "State": "Состояние",
  "State Machine": "Просмотр состояний",
  "Step": "Шаг",
  "Stepped layers, independent of the carrying wrist. Keys preserve the rigid artwork and IK; hand silhouettes cover the grip.": "Глубина переключается по ключам независимо от несущей кисти. Рисунок и IK сохраняются; кисти закрывают хват.",
  "Stroke": "Обводка",
  "Stroke Width": "Толщина обводки",
  "Style Set": "Стиль",
  "Supports families:": "Семейства скелетов:",
  "Symmetry": "Симметрия",
  "Target": "Назначение",
  "Target Bone": "Целевая кость",
  "Target Slot": "Целевое крепление",
  "Target slot:": "Целевое крепление:",
  "Template": "Основа",
  "Template Slot": "Крепление основы",
  "Test animation": "Проверка анимации",
  "These sliders update the active entity immediately in canvas, animation preview and save data.": "Ползунки сразу обновляют объект на холсте, в анимации и в сохраняемых данных.",
  "This layer is empty.": "Этот слой пуст. Нарисуйте фигуру или импортируйте изображение.",
  "Time (ms)": "Время, мс",
  "Toggle ms/frames": "Миллисекунды / кадры",
  "Tokens:": "Цвета:",
  "Torso": "Туловище",
  "Trajectory: None": "Траектория: нет",
  "Transition": "Переход",
  "Tree Example": "Пример дерева",
  "Tree Rig": "Скелет дерева",
  "Undo": "Отменить",
  "Uniform Scale": "Равномерный масштаб",
  "Unlock All Slots": "Разблокировать все крепления",
  "Unspecified": "Не задано",
  "Unwrapped": "Полный оборот",
  "Up": "Выше",
  "Upper-body clip overlay (plays simultaneously with base clip)": "Клип верхней части тела (одновременно с основным)",
  "Usage": "Использование",
  "Use Group Binding / Unbind": "Наследовать привязку группы / отвязать",
  "Viewport": "Область просмотра",
  "Visible": "Видимый",
  "Visual Bones": "Кости рисунков",
  "Visual Mode": "Режим отображения",
  "Visual Mode:": "Режим отображения:",
  "Weight brush mode": "Режим кисти весов",
  "Width": "Ширина",
  "Wind Starter": "Пример ветра",
  "Workflow": "Задача",
  "X-Ray joint markers and labels": "Маркеры и подписи суставов",
  "Z Index": "Порядок глубины",
  "Z Offset": "Смещение глубины",
  "Zoom in": "Приблизить",
  "Zoom out": "Отдалить",
  "active": "активное",
  "blend": "смешивание",
  "click state or edge to inspect": "Выберите состояние или переход для просмотра",
  "document": "документ",
  "e.g. horse, human, dragon…": "например, человек, лошадь, дракон…",
  "easing:": "сглаживание:",
  "entry": "начальное",
  "fps": "кадров/с",
  "head": "голова",
  "keys:": "ключи:",
  "ms": "мс",
  "ms ·": "мс ·",
  "of": "из",
  "of 3": "из 3",
  "overlay ·": "рисунок ·",
  "px": "пикс.",
  "px /": "пикс. /",
  "px ·": "пикс. ·",
  "px)": "пикс.)",
  "read-only": "только просмотр",
  "rig units": "единицы скелета",
  "runtime": "воспроизведение",
  "selected overlay:": "выбранный рисунок:",
  "shapes": "фигуры",
  "speed×": "скорость ×",
  "states ·": "состояний ·",
  "to preview it here": "для предпросмотра",
  "tracks": "дорожек",
  "transitions": "переходов",
  "triangles": "треугольников",
  "vertices ·": "вершин ·",
  "wt:": "вес:",
  "° · Bend": "° · изгиб",
  "· Depth:": "· Глубина:",
  "· RIGHT and LEFT · Normal / Rig Colors / Depth Colors / Skeleton. Includes SVG, PNG and diagnostic JSON.": "· Справа и слева · Обычный вид / Цвета скелета / Цвета глубины / Скелет. SVG, PNG и JSON диагностики.",
  "· pivot": "· опора",
  "· pivot:": "· опора:",
  "× Unequip": "× Снять",
  "— none —": "— нет —",
  "↑ Upper:": "↑ Верх:",
  "↓ Lower:": "↓ Низ:",
  "DRAW": "Рисунок",
  "RIG": "Скелет",
  "ANIMATE": "Анимация",
  "brush": "Кисть",
  "eraser": "Ластик",
  "select": "Выделение",
  "move": "Перемещение",
  "lasso": "Лассо",
  "rect-select": "Выделение рамкой",
  "eyedropper": "Пипетка",
  "fill": "Заливка",
  "rect": "Прямоугольник",
  "ellipse": "Эллипс",
  "path": "Контур",
  "bone": "Кость",
  "mesh": "Сетка",
  "weight": "Веса",
  "weights": "Веса",
  "raster": "Растр",
  "vector": "Вектор",
  "group": "Группа",
  "artwork": "Рисунок",
  "rig": "Скелет",
  "depth": "Глубина",
  "bones": "Кости",
  "pivots": "Точки опоры",
  "z": "Порядок глубины",
  "low": "Низкое",
  "medium": "Среднее",
  "high": "Высокое",
  "add": "Добавить",
  "subtract": "Вычесть",
  "replace": "Заменить",
  "smooth": "Сгладить",
  "rigid": "Жёсткая привязка",
  "weighted": "Веса сетки",
  "Unbound": "Без привязки",
  "tx": "Смещение X",
  "ty": "Смещение Y",
  "rotation": "Поворот",
  "scaleX": "Масштаб X",
  "scaleY": "Масштаб Y",
  "item-part": "Часть предмета", "entity-visual": "Рисунок объекта", "face-overlay": "Деталь лица",
  "Root": "Корень", "trunk": "Ствол",
  "branch_left": "Левая ветвь", "branch_left_mid": "Середина левой ветви", "branch_left_tip": "Конец левой ветви",
  "branch_right": "Правая ветвь", "branch_right_mid": "Середина правой ветви", "branch_right_tip": "Конец правой ветви",
  "branch_top": "Верхняя ветвь", "branch_top_mid": "Середина верхней ветви", "branch_top_tip": "Конец верхней ветви",
  "leaves_left": "Левая крона", "leaves_left_tip": "Край левой кроны", "leaves_right": "Правая крона", "leaves_right_tip": "Край правой кроны", "leaves_top": "Верхняя крона", "leaves_top_tip": "Край верхней кроны",
  "Tree Idle Wind": "Дерево на ветру", "Continuous Rotation": "Непрерывное вращение",
  "Pelvis": "Таз", "Spine": "Позвоночник",
  "Shoulder L": "Левое плечо", "Elbow L": "Левый локоть", "Hand L": "Левая кисть", "Shoulder R": "Правое плечо", "Elbow R": "Правый локоть", "Hand R": "Правая кисть",
  "Hip L": "Левое бедро", "Knee L": "Левое колено", "Foot L": "Левая стопа", "Hip R": "Правое бедро", "Knee R": "Правое колено", "Foot R": "Правая стопа"
};
export function uiLabel(value: string) { return labels[value] ?? value; }
